from dotenv import load_dotenv, find_dotenv
from os import getenv


load_dotenv(find_dotenv())

SECRETS_WRITER_ACC = getenv('SECRETS_WRITER_ACC')
SECRETS_WRITER_PWD = getenv('SECRETS_WRITER_PWD')

SECRETS_READER_ACC = getenv('SECRETS_READER_ACC')
SECRETS_READER_PWD = getenv('SECRETS_READER_PWD')

SECRETS_DB = getenv("SECRETS_DB")

MONGO_HOST = getenv("MONGO_HOST")

# print(SECRETS_WRITER_ACC, SECRETS_WRITER_PWD, SECRETS_READER_ACC, SECRETS_READER_PWD, SECRETS_DB, MONGO_HOST)




